### ISSUE TITLE
Storyboard / SwinjectStoryboard How to set the module name of a storyboard programmatically?

### ISSUE THREAD

**Issue by waelsaad** [Swinject/SwinjectStoryboard#102]
Hi,

How can I set module for a storyboard programmatically and also for all of its UI content?

The reason is because the storyboard itself is in an app that references a framework which contains the viewcontroller. 

So looking at this screenshot I can tell the storyboard to point to the Presentation Framework. I'd like to know if there is a better and easier way to set the module programmatically.

![screen shot 2018-07-13 at 9 14 26 am](https://user-images.githubusercontent.com/4057766/42664379-ceeb1286-867d-11e8-8eb6-a465708c3a94.png)

**Comment by jakubvano** [comment]
This issue is not related to the `SwinjetStoryboard`. You have better chance of getting the answer in the related [SO querstion](https://stackoverflow.com/questions/51315787/storyboard-swinjectstoryboard-how-to-set-the-module-name-of-a-storyboard-progr).
