### ISSUE TITLE
Carthage clean build fails

### ISSUE THREAD

**Issue by savelii** [Swinject/SwinjectStoryboard#119]
If I make clean Carthage update (removing Cartfile.resolved and Carthage directory before) then I get following error, second attempt (without removing Cartfile.resolved and Carthage directory) is success

carthage version 0.33.0 (Latest)
Xcode Version 10.2.1 (10E1001) (Latest)

`Users-MacBook-Pro:TestProject user1$ carthage update  --platform iOS
*** Fetching SwinjectStoryboard
*** Fetching Swinject
*** Checking out Swinject at "2.6.0"
*** Checking out SwinjectStoryboard at "2.2.0"
*** xcodebuild output can be found in /var/folders/bc/lmyvcpn15wvb2s4bx6q826c00000gn/T/carthage-xcodebuild.ARtdrX.log
*** Building scheme "Swinject-iOS" in Swinject.xcodeproj
*** Building scheme "SwinjectStoryboard-iOS" in SwinjectStoryboard.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/user1/Xcode\ Projects/TestProject/Carthage/Checkouts/SwinjectStoryboard/SwinjectStoryboard.xcodeproj -scheme SwinjectStoryboard-iOS -configuration Release -derivedDataPath /Users/user1/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2.1_10E1001/SwinjectStoryboard/2.2.0 -sdk iphonesimulator -destination platform=iOS\ Simulator,id=69D6695B-61A4-4C4F-9E6C-B95C2CA04EE5 -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/user1/Xcode Projects/TestProject/Carthage/Checkouts/SwinjectStoryboard)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/bc/lmyvcpn15wvb2s4bx6q826c00000gn/T/carthage-xcodebuild.ARtdrX.log`

[carthage-xcodebuild.ARtdrX.log](https://github.com/Swinject/SwinjectStoryboard/files/3194074/carthage-xcodebuild.ARtdrX.log)

**Comment by jakubvano** [comment]
This works fine on my machine with the same Xcode & Carthage versions. Have you tried clearing derived data / carthage caches (`~/Library/Cache/org.carthage.*`)?

**Comment by savelii** [comment]
No, will try and let you know

**Comment by savelii** [comment]
clearing carthage caches (~/Library/Cache/org.carthage.*) helped, thanks
