### ISSUE TITLE
+load method violation 

### ISSUE THREAD

**Issue by mpdifran** [Swinject/SwinjectStoryboard#124]
After running a project in Xcode 11.0 beta (11M336w), I get the following message:

```
Swift class extensions and categories on Swift classes are not allowed to have +load methods
```

Should we remove this override? How integral is it to `SwinjectStoryboard`?

**Comment by jakubvano** [comment]
We might be able to replace the `load` call here in the same way as in #114. 
If not, we could extract it to the public method and require consumer to call it explicitly from the application code.

Completely removing it would definitely break some features - from the top of my head referenced storyboards & container view controllers.

**Comment by mpdifran** [comment]
I've also read that in iOS 13 view controllers instantiated from a storyboard can be passed a context parameter, which would be super useful for injecting dependencies. Haven't looked too much into it yet though.

**Comment by CornellSkyers** [comment]
I made modifications and was able to run my sample code that had previously been crashing with this error. **This may not be the correct solution, I was just looking for a quick fix.** I replaced the load method in 'UIStoryboard+Swizzling.m' with the following:

`__attribute__((constructor)) static void swinjectStoryboardSetupEntry(void) {
        Class class = [UIStoryboard class];

        SEL originalSelector = @selector(storyboardWithName:bundle:);
        SEL swizzledSelector = @selector(swinject_storyboardWithName:bundle:);

        Method originalMethod = class_getClassMethod(class, originalSelector);
        Method swizzledMethod = class_getClassMethod(class, swizzledSelector);

        BOOL didAddMethod =
        class_addMethod(class,
                        originalSelector,
                        method_getImplementation(swizzledMethod),
                        method_getTypeEncoding(swizzledMethod));

        if (didAddMethod) {
            class_replaceMethod(class,
                                swizzledSelector,
                                method_getImplementation(originalMethod),
                                method_getTypeEncoding(originalMethod));
        } else {
            method_exchangeImplementations(originalMethod, swizzledMethod);
        }
}`

**Comment by mpdifran** [comment]
This is probably safe to close now, I believe it's fixed in the latest version.
