### ISSUE TITLE
Stable version

### ISSUE THREAD

**Issue by CurlyHeir** [Swinject/SwinjectStoryboard#14]
Hi, 
I'm wondering if i should use SwinjectStoryboard in my production code, this project has only 1 release 2 months ago, when will be production-ready version?

**Comment by yoichitgy** [comment]
Hi. No ETA for this project with Swinject v2, but Swinject v1 contains SwinjectStoryboard as a stable version.

**Comment by CurlyHeir** [comment]
fair enough, i'm new in Swinject so i didn't knew. 
thx for fast reply 👍
