### ISSUE TITLE
When is the new version going to be released?

### ISSUE THREAD

**Issue by sumit-anantwar** [Swinject/SwinjectStoryboard#141]
We are still using the workaround for the `ServiceKeyOption` non-conformance.
I am aware that the changes are already merged into master, but they haven't been released.
I just wanted to know if anything has been scheduled yet.

**Comment by adamayoung** [comment]
Is this project still active? When will we see a new release? The last release was 1 Apr 2019!

**Comment by yourshinsuke** [comment]
@jakubvano
@tkohout 
@yoichitgy

**Comment by sumit-anantwar** [comment]
Any update on this?

**Comment by teejayhh** [comment]
Looks like its abandoned, I guess its time to move on.

**Comment by ChediB** [comment]
+1

**Comment by ChediB** [comment]
@yoichitgy 
@mpdifran

**Comment by mpdifran** [comment]
@ChediB thanks for bringing to our attention! Sounds like the fix is already in master, I'll prioritize a release here ASAP!

**Comment by yoichitgy** [comment]
Thanks @mpdifran! 😃 
I merged some PRs for Swift 5 and Xcode 12.5 too🚀

As far as I checked, unit tests for iOS and tvOS success, but fail for macOS. I think we can make a release with the macOS problem as a known issue.
![Screen Shot](https://user-images.githubusercontent.com/965994/124293254-6cfa0e80-db91-11eb-9fb2-d167f8e14d52.png)

**Comment by yoichitgy** [comment]
I'm still not sure we still need PR #140🙏

**Comment by mpdifran** [comment]
@yoichitgy awesome thanks! I'll spend a bit of time to see if I can get the macOS tests passing, but I won't treat it as a blocker. I'll take a look at #140 as well.

**Comment by mpdifran** [comment]
Just released version 2.2.1 of SwinejctStoryboard! 

It's my first time doing the release, please let me know if anything is wrong and I'll try to rectify it.
