### ISSUE TITLE
Carthage swinjectStoryboard failed

### ISSUE THREAD

**Issue by michael88886** [Swinject/SwinjectStoryboard#142]
I have this failed log when using carthage for SwinjectStoryboard framework:

/Users/$USER/Desktop/Projects/RxWeather/Carthage/Checkouts/SwinjectStoryboard/Sources/SwinjectStoryboardOption.swift:12:17: error: type 'SwinjectStoryboardOption' does not conform to protocol 'ServiceKeyOption'
internal struct SwinjectStoryboardOption: ServiceKeyOption {
                ^
Swinject.ServiceKeyOption:3:10: note: protocol requires function 'hash(into:)' with type '(inout Hasher) -> ()'
    func hash(into: inout Hasher)
         ^
/Users/$USER/Desktop/Projects/RxWeather/Carthage/Checkouts/SwinjectStoryboard/Sources/SwinjectStoryboardOption.swift:12:17: note: do you want to add protocol stubs?
internal struct SwinjectStoryboardOption: ServiceKeyOption {
                ^

** ARCHIVE FAILED **

The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
	CompileSwift normal armv7
(4 failures)

I have attached my log file.

[carthage-xcodebuild.AwAwXw.log](https://github.com/Swinject/SwinjectStoryboard/files/4250031/carthage-xcodebuild.AwAwXw.log)

**Comment by alekzernov** [comment]
I have exactly the same error

**Comment by bamohammad** [comment]
I have same issue

**Comment by michael88886** [comment]
My temporary solution is to download the project and correct the code by adding implementation for the "hash" function.

After that, I upload my corrected version to a new git, and my CI is building SwinjectStoryboard from there.

It seems this problem has been called out since Swinject v2.7.0. Hope some will fix this problem soon and have the new release.
