### ISSUE TITLE
Swift Package Manager XCode 12.0

### ISSUE THREAD

**Issue by Trubianov** [Swinject/SwinjectStoryboard#149]
Im getting error on Xcode 12.0 with SPM - "the package product 'swinject' requires minimum platform version 9.0 for the ios platform, but this target supports 8.0"
I modified in Package.swift  ios version to 9 and it works, but this files places in Derived Data folder, ant it's temp solution. So please update it ASAP.
```
platforms: [
        .macOS(.v10_10),
        .iOS(.v8), // CHANGE to v9
        .tvOS(.v9),
    ],
```

**Comment by dimawushu** [comment]
+, same, it sheet

**Comment by Trubianov** [comment]
> +, same sheet

u can do it manually but don't clean Derived data folder, and dont gorget Resolve dependencies, just in case it helps you.

**Comment by juliobailon** [comment]
There is a pull request for this. Not sure when it is going to be merged

**Comment by omarmasripro** [comment]
Hey guys,

Any update about this ?

**Comment by BarredEwe** [comment]
This was recently resolved in the pull request.

**Comment by mpdifran** [comment]
Yup! the Package.swift file now specifies a minimum version of iOS 9.
