### ISSUE TITLE
Rename registerForStoryboard to avoid misunderstanding

### ISSUE THREAD

**Issue by yoichitgy** [Swinject/SwinjectStoryboard#21]
It looks good to rename `registerForStoryboard` to `injectOnInstantiationByStoryboard` or something else to avoid misunderstanding that `resolve` method (especially with arguments) can be used as a pair with `registerForStoryboard`.

Related issue:
https://github.com/Swinject/Swinject/issues/153

**Comment by yoichitgy** [comment]
@jakubvano, do you have good idea for the naming?

**Comment by jakubvano** [comment]
I agree that naming is confusing - it is odd that we are passing `initCompleted` closure to method called `register...`, when for normal registrations we are passing `factory` to `register` methods. Maybe reflecting this relationship with `initCompleted` in API might be helpful to understand what is going on:
```
container.storyboardService(MyViewController.self).initCompleted { r, c in ... }
```

or

```
container.storyboardInitCompleted(MyViewController.self) { r, c in ... }
```

**Comment by yoichitgy** [comment]
Thanks @jakubvano for your nice idea😃

I prefer the latter one `storyboardInitCompleted` for its simplicity. If you are ok too, let's take it as our spec.
