### ISSUE TITLE
Code example from "Implicit Instantiation from "Main" Storyboard" section doesn't compile

### ISSUE THREAD

**Issue by Kievkao** [Swinject/SwinjectStoryboard#26]
When I try to implement extension for SwinjectStoryboard (with my own types of course), I get a compilation error "Value of type 'Container' has no member 'storyboardInitCompleted' "

**Comment by jakubvano** [comment]
Thanks for pointing out this problem! 👍 

`storyboardInitCompleted` is new name for method `registerForStoryboard` (see #22). However, this change has not yet been released, but is already reflected in documentation on master branch.

You can view documentation in line with latest release [here](https://github.com/Swinject/SwinjectStoryboard/tree/1.0.0-beta.2#implicit-instantiation-from-main-storyboard).

**Comment by Kievkao** [comment]
Thanks for the so quick answer! :)
You do a great job, guys!
