### ISSUE TITLE
registerForStoryboard closure is never called on child container using AssemblyType

### ISSUE THREAD

**Issue by sashagood** [Swinject/SwinjectStoryboard#31]
Hi, I saw the similar question here but we can unite them later.
I'm trying to cook Swinject with VIPER and struggling the issue with `registerForStoryboard` on child container.
Here is the structure of how I'm trying to implement this. I want to achieve having one `AssemblyType` and `Assembler` per module.
Two modules:

```
class TabBarAssembler {
    
    let assembler: Assembler
    
    init(parentAssembler: Assembler) {
        assembler = try! Assembler(assemblies: [TabBarAssembly()], parentAssembler: parentAssembler)
    }
}

class TabBarAssembly: AssemblyType {
    
    func assemble(container: Container) {
        container.register(SketchesListAssembler.self) { r in
            let parentAssembler = r.resolve(TabBarAssembler.self)!
            return SketchesListAssembler(parentAssembler: parentAssembler.assembler)
        }
        container.registerForStoryboard(TabBarViewController.self) { (r, controller: TabBarViewInputProtocol) in
            let presenter = r.resolve(TabBarPresenterProtocol.self, argument: controller)!
            controller.presenter = presenter
        }
        container.register(TabBarInteractorInputProtocol.self) { _ in
            TabBarInteractor()
        }
        container.register(TabBarPresenterProtocol.self) { (r, view: TabBarViewInputProtocol) in
            let interactor = r.resolve(TabBarInteractorInputProtocol.self)!
            let router = r.resolve(TabBarRouterInputProtocol.self)!
            let presenter = TabBarPresenter(view: view, interactor: interactor, router: router)
            interactor.presenter = presenter
            return presenter
        }
        container.register(TabBarRouterInputProtocol.self) { r in
            let router = TabBarRouter()
            router.sketchesListAssembler = r.resolve(SketchesListAssembler.self)
            return router
        }
    }
}

class SketchesListAssembler {
    
    private let assembler: Assembler
    
    init(parentAssembler: Assembler) {
        assembler = try! Assembler(assemblies: [SketchesListAssembly()], parentAssembler: parentAssembler)
    }
    
}

class SketchesListAssembly: AssemblyType {
    
    func assemble(container: Container) {
        container.registerForStoryboard(SketchesListViewController.self) { (r, controller: SketchesListViewInputProtocol) in
            let presenter = r.resolve(SketchesListPresenterProtocol.self, argument: controller)!
            controller.presenter = presenter
        }
        container.register(SketchesListInteractorInputProtocol.self) { _ in
            SketchesListInteractor()
        }
        container.register(SketchesListPresenterProtocol.self) { (r, view: SketchesListViewInputProtocol) in
            let interactor = r.resolve(SketchesListInteractorInputProtocol.self)!
            let router = r.resolve(SketchesListRouterInputProtocol.self)!
            let presenter = SketchesListPresenter(view: view, interactor: interactor, router: router)
            interactor.presenter = presenter
            return presenter
        }
        container.register(SketchesListRouterInputProtocol.self) { _ in
            SketchesListRouter()
        }
    }
}
```
`registerForStoryboard` is used in both of them.  And as you can see I'm passing `Assembler` to `SketchesListAssembler` as part of parent/child relationship. Resolver clusures are called in `TabBarAssembly` but never called in `SketchesListAssembly`.

The question is how to implement this in a proper way and to get `SketchesListAssembly` closures called? 
  
Versions:
'Swinject', '2.0.0-beta.2'
'SwinjectStoryboard', '1.0.0-beta.2'

**Comment by sashagood** [comment]
Here you are storyboard hierarchy. It should help to understand.
![monosnap 2016-11-22 16-20-46](https://cloud.githubusercontent.com/assets/414200/20525315/cea479f0-b0cf-11e6-88e4-06addf78abb1.png)

**Comment by yoichitgy** [comment]
I'm not sure what was the problem in the example code. Was `assemble` method of `SketchesListAssembly` called? Maybe providing a minimal simple project to reproduce the issue is helpful to check the problem.

**Comment by yoichitgy** [comment]
Although the architecture might be different from yours, this sample project using Swinject might be helpful for you:
https://github.com/ppamorim/swinjected

**Comment by sashagood** [comment]
@yoichitgy Thanks! I'll check the repo. 
Sorry for answering so late. I'll be back soon with a sample project.

**Comment by yoichitgy** [comment]
Sorry, I intended to post the comment in another issue, but [the sample](https://github.com/ppamorim/swinjected) might be helpful for you.
https://github.com/Swinject/SwinjectStoryboard/issues/27#issuecomment-263877573

**Comment by sashagood** [comment]
Hi, @yoichitgy. I created sample project representing the problem. As I said before closures of `SketchesListAssembly` are never called.

**Comment by yoichitgy** [comment]
Thanks @sashagood for the sample project👍 I'll check it after I release Swinject v2.0.0.

**Comment by yoichitgy** [comment]
I reminded myself of this issue.

**Comment by jakubvano** [comment]
@sashagood I've ran your test project - issue there seems to be that you are initialising `SwinjectStoryboard` with `tabBarAssembler.assembler` which does not contain registrations from `SketchesListAssembly`.
Registrations in child container/assembler (`SketchesListAssembler`) are not available in parent (`TabBarAssembler`). It works the other way around.

As this is quite old issue, and does not (AFAICT) describe a bug in Swinject I will close this. Feel free to reopen if you have further questions.
