### ISSUE TITLE
Test target resolve issue

### ISSUE THREAD

**Issue by rb-de0** [Swinject/SwinjectStoryboard#32]
Hi, I have a question about dependent injection in Unit Test.
I use SwinjectStoryboard as follows to inject dependency to top viewController.

```Swift
extension SwinjectStoryboard {
    class func setup() {
        
        defaultContainer.storyboardInitCompleted(TopViewController.self){ _, c in
            c.repository = Repository()
        }
    }
}
```

In normal target, injection is success. But, injection is failure in tests target.
I think that there is a issue about controllerType of SwinjectStoryboardOption. 
In registration phase, controllerType is 'AppNameTests.TopViewController. But, in resolving phase, controllerType is 'AppName.TopViewController'.

Is there any solution about this?

#### Env
Swinject branch master (using CocoaPods)
SwinjectStoryboard branch master (using CocoaPods)
Xcode 8.1 Swift 3.0
iOS 10.1 Device

**Comment by yoichitgy** [comment]
It looks strange that the module name part of the type full name is different at registration and resolution phases if `TopViewController` is defined only in `AppName` module. Can you provide a simple sample project to reproduce the issue?

**Comment by rb-de0** [comment]
Sorry, The cause was that we added ViewController to the test target.
When file was excluded, it worked normally.
Thanks!!
