### ISSUE TITLE
ViewControllers instantiated with segues

### ISSUE THREAD

**Issue by oronbz** [Swinject/SwinjectStoryboard#36]
Hi, 
How can I register controllers which are instantiated by segues and especially, how they are resolved?

**Comment by danielchristopher1** [comment]
Wondering the same thing.

**Comment by jakubvano** [comment]
Hi,
When `UIViewController` is instantiated by segue, internally `UIStoryboard.instantiateViewController(identifier:)` method is being used. So you register it the same way as if you were to instantiate it manually, i.e. by `registerForStoryboard` (or `storyboardInitCompleted` in 1.0.0-beta.3). More info can be found (here)[https://github.com/Swinject/SwinjectStoryboard#registration]

**Comment by yoichitgy** [comment]
@oronbz, @danielchristopher1, was this issue resolved?

**Comment by oronbz** [comment]
Yes, it works automatiucally thanks
