### ISSUE TITLE
Question about storyboardInitCompleted

### ISSUE THREAD

**Issue by josephbeuysmum** [Swinject/SwinjectStoryboard#40]
Just for clarity: registerForStoryboard has been replaced with storyboardInitCompleted. And it's just a straight swap, no additional code or other changes needed?

**Comment by yoichitgy** [comment]
You are right. The method was just renamed.
https://github.com/Swinject/SwinjectStoryboard/releases/tag/1.0.0-beta.3

**Comment by josephbeuysmum** [comment]
So it looks like your suggestions might be helpful @yoichitgy, thanks [again]. What I'm finding with the below code is that two instances of UserProxy are created, but only the first is injected. Would that be what you expect? All the proxies and the view are just stub classes btw.

`		defaultContainer.register( UserProxy.self )
		{
			responder in UserProxy( api: responder.resolve( APIService.self )! )
		}.inObjectScope( .container ).initCompleted(
			{
				responder, userProxy in
				userProxy.data = responder.resolve( DataProxy.self )!
			}
		)
		
		defaultContainer.register( DataProxy.self )
		{
			responder in DataProxy(
				user: responder.resolve( UserProxy.self )!,
				api: responder.resolve( APIService.self )!
			)
		}.inObjectScope( .container )
		
		defaultContainer.register( APIService.self )
		{
			responder in APIService()
		}.inObjectScope( .container ).initCompleted(
			{
				responder, api in
				api.user = responder.resolve( UserProxy.self )!
			}
		)
		
		defaultContainer.storyboardInitCompleted( ViewController.self )
		{
			resolvable, viewController in
			viewController.user = resolvable.resolve( UserProxy.self )!
			viewController.api = resolvable.resolve( APIService.self )!
			viewController.data = resolvable.resolve( DataProxy.self )!
		}
`

**Comment by jakubvano** [comment]
Indeed, observer behavior is in thisn case expected: As noted in [CircularDependency#Remark](https://github.com/Swinject/Swinject/blob/master/Documentation/CircularDependencies.md#remark)

> When resolving circular dependencies one of the factory methods (one containing resolution of circular dependency) migth be invoked twice.

In this case this holds for `UserProxy` as it has circular dependency with `APIService` referenced from factory method.
While the same holds for `DataProxy` (circular dependency with `UserProxy` from factory method), it's method does not need to be called twice: difference with previous case is the order of resolution - `UserProxy` is resolved first.

Anyway - this are all side effects of `Container` implementation, and shouldn't be relevant in most cases. When they are important, you can avoid multiple factory invocations by moving all circular dependency resolutions to `initCompleted` (i.e. changing constructor to property dependency), as suggested in  [CircularDependency#Remark](https://github.com/Swinject/Swinject/blob/master/Documentation/CircularDependencies.md#remark).

**Comment by josephbeuysmum** [comment]
D'oh! My rushed reading of the docos, sorry @jakubvano. I noticed the bit you quoted in your second para, but not the "moving all circular dependency resolutions to initCompleted" bit. My bad. Thanks for the clarification, I will move my injections to `initCompleted`.

**Comment by josephbeuysmum** [comment]
Yes, that works nicely @jakubvano, thank you.

**Comment by josephbeuysmum** [comment]
dammit, these comments should have been in this thread instead: https://github.com/Swinject/Swinject/issues/219

I must have been tired yesterday.

**Comment by yoichitgy** [comment]
Closing this issue because it looks resolved😉
