### ISSUE TITLE
Add Swift Package Manager Support

### ISSUE THREAD

**Issue by marlontojal** [Swinject/SwinjectStoryboard#42]
Since swinject has SPM support, this should have it also

**Comment by yoichitgy** [comment]
Thanks @marlontojal for posting a request👍

Do you have good idea to set up SPM for an Xcode project? SwinjectStoryboard is used to develop iOS/macOS/tvOS UI. I'm not familiar with SPM for an Xcode project.

We tried in PR #39 but couldn't complete. Would you help us?

**Comment by yoichitgy** [comment]
Thanks @marlontojal for the request. I'll add SPM support after it supports iOS/macOS/tvOS targets☀️

**Comment by marekpridal** [comment]
SPM should support iOS, macOS and tvOS targets 🙂

**Comment by igorkulman** [comment]
With XCode 11 maybe it is time to revisit this. Swinject/SwinjectStoryboard and Swinject/SwinjectAutoregistration already support SPM

**Comment by jakubvano** [comment]
Indeed, it would be usefull with Xcode 11

**Comment by armintelker** [comment]
With xcode 11 we really should think about this again.

**Comment by adamayoung** [comment]
+1 on this.

**Comment by BarredEwe** [comment]
I added support swift package manager https://github.com/Swinject/SwinjectStoryboard/pull/136.
☀️☀️☀️

**Comment by mpdifran** [comment]
This has finally been merged! Closing this ticket now.
