### ISSUE TITLE
Objective-C class method 'initialize', which is not guaranteed to be invoked by Swift and will be disallowed in future versions 

### ISSUE THREAD

**Issue by yoichitgy** [Swinject/SwinjectStoryboard#45]
Posted by @mrkd: https://github.com/Swinject/Swinject/issues/238

## Objective-C class method 'initialize', which is not guaranteed to be invoked by Swift and will be disallowed in future versions

Xcode - Version 8.3 (8E162), Swift 3.1
  - Swinject (2.0.0)
  - SwinjectStoryboard (1.0.0):
    - Swinject (= 2.0.0)

/Pods/SwinjectStoryboard/Sources/Storyboard+Swizzling.swift:25:30: Method 'initialize()' defines Objective-C class method 'initialize', which is not guaranteed to be invoked by Swift and will be disallowed in future versions

**Comment by mpdifran** [comment]
I think this can be fixed by migrating this extension to Objective-C. Are there any objections to that? I can take a crack at it.

**Comment by charles-oder** [comment]
wouldn't that kinda defeat the purpose of this being an injection framework for Swift?

**Comment by mpdifran** [comment]
The project already uses an Objective-C class for the base storyboard subclass. Rewriting the swizzle extension in Objective-C shouldn't affect the public interface either. 

That is assuming this can be done this way; I've looked into it a bit, and it seems like the swizzle extension references some static Swift methods, and I can't import `SwinjectStoryboard-Swift.h` for some reason.

**Comment by yoichitgy** [comment]
I agree with @mpdifran's idea. Writing the extension in Objective-C sounds good. Originally I just tried write code in Swift as much as possible, but now I think writing the extension in Objective-C is simpler.

**Comment by mpdifran** [comment]
@yoichitgy I've got most of the work done, but I'm stuck with the `import SwinjectStoryboard-Swift.h` problem. Mind taking a look at my branch if I push it up?

**Comment by yoichitgy** [comment]
@mpdifran, I answered in the pull request😃

**Comment by CurlyHeir** [comment]
@yoichitgy @mpdifran any progress?

**Comment by mpdifran** [comment]
Waiting on @yoichitgy for advice on how to proceed for the last `initialize()` warning. I'll update to remove the merge conflict though.

**Comment by yoichitgy** [comment]
v1.1.2 fixed the issue. Thanks @mpdifran 👍👍👍
