### ISSUE TITLE
SwinjectStoryboard + Assemblies

### ISSUE THREAD

**Issue by Mackarous** [Swinject/SwinjectStoryboard#50]
I am having trouble understanding how to combine different assemblies/assemblers with SwinjectStoryboard. I am using the implicit storyboard extension, but I want to separate assemblies for clean code.

Here is an example:
```swift
extension SwinjectStoryboard {
    public static func setup() {
        defaultContainer.register(ColorRandomizer.self) { _ in
            DefaultColorRandomizer()
        }
        defaultContainer.register(NameGenerator.self) { _ in
            DeveloperNameGenerator()
        }
        defaultContainer.storyboardInitCompleted(ViewController.self) { r, c in
            c.colorRandomizer = r.resolve(ColorRandomizer.self)
            c.nameGenerator = r.resolve(NameGenerator.self)
        }
    }
}
```

This works for the initial view controller, but let's say I have another assembly that I want to assemble. Am I supposed to do this?
```swift
let assembler = Assembler([SomeAssembly()], container: SwinjectStoryboard.defaultContainer)
```
Also I understand that I need to maintain a strong reference to the assembler, so should I have only 1 assembler, and apply assemblies when I need them? Should the assembler be in the `AppDelegate`?

**Comment by mpdifran** [comment]
You're pretty close to the correct solution. Rather than using the `SwinjectStoryboard` extension, just create Assemblies for your view controllers:

    class ViewControllerAssembly: Assembly {
        
        func assemble(container: Container) {
            container.storyboardInitCompleted(ViewController.self) { r, c in
                c.colorRandomizer = r.resolve(ColorRandomizer.self)
                c.nameGenerator = r.resolve(NameGenerator.self)
            }
            // etc
        }
    }

Then provide them to your assembler exactly how you specified:

    let assembler = Assembler([ViewControllerAssembly()], container: SwinjectStoryboard.defaultContainer)

I like to have my `AppDelegate` maintain the only reference to my single `Assembler`, which you also alluded to.

Let me know if you have any other questions.

**Comment by Mackarous** [comment]
Perfect! Thanks a lot!

**Comment by yoichitgy** [comment]
Thanks @mpdifran for answering!

**Comment by channguyen** [comment]
@mpdifran  So in the end, what do you have in AppDelegate?
```
extension SwinjectStoryboard {
  class func setup() {
    do {
      try Assembler(
        assemblies: [NetAssembly(), SecurityAssembly(), PermissionAssembly(), ViewControllerAssembly()],
        container: defaultContainer
      )
    } catch let error {
      print("Fatal: \(error.localizedDescription)")
    }
  }
}```

Do I need to keep a reference to `assembler` at all?
