### ISSUE TITLE
OSX initialization 

### ISSUE THREAD

**Issue by kkrawczynski** [Swinject/SwinjectStoryboard#57]
Hi guys,

im doing sample OSX project and i have huge problems with Swinject Storyborad initialization  - i was using it for iOS and never had any issues.

I've tried both: Implicit and Explicit Instantation and **none** of them works 

- **Implicit** crashes entire app -i assume because of all dependencies are resolved after app startup and after Initial View Controller is loaded (which expect all dependencies to be resolved before launch)
- **Explicit** (removing initial storyboard in plist and trying to set up in NSApplicationDelegate's _applicationDidFinishLaunching_) causes app never to launch. _applicationDidFinishLaunching_ is never called when entry from plist is removed. Where to put initialization code?

I also found that when i use Implict initialization _storyboardInitCompleted_ is **never** called:

```
extension SwinjectStoryboard{
    public static func setup() {
        defaultContainer.register(PlayerVCViewModelling.self){
            c in
            PlayerViewModel()
        }

        defaultContainer.storyboardInitCompleted(PlayerViewController.self){
            r,c in
            c.playerViewModel = r.resolve(PlayerVCViewModelling.self)
        }
    }
}
```

Can anyone please explain or give any tips how to properly instantiate Swinject Storyboard for OSX project?

Thanks

**Comment by yoichitgy** [comment]
I don't see problems here. It might be able to check the problem if you provide a sample project to reproduce the problem.

**Comment by kkrawczynski** [comment]
Hi Yoichi,

thanks for coming back. I've already found  a solution but ive created sample project for you to look at.

I figured out that there is a quite difference between OSX and iOS and Swinject relies on how and where you resolve your init dependencies in OSX.   

If you try to resolve your dependencies in **root view controller's viewDidLoad** and you want SwinjectStoryboard to inject it **automatically** then it will crash because nothing is resolved yet (i suppose including swinject itself).
This is not the case for **viewWillAppear** as in this point everything is already initialized.  

Please look at sample below and let me know what do you think.
Thanks

[SwinjectStoryboard_OSX.zip](https://github.com/Swinject/SwinjectStoryboard/files/1179652/SwinjectStoryboard_OSX.zip)

**Comment by yoichitgy** [comment]
Thanks @kkrawczynski for the investigation and the sample project👍👍👍 I'll look into it!

**Comment by yoichitgy** [comment]
@kkrawczynski, I'm sorry that I couldn't take time to investigate the issue yet. Did you solve the issue by yourself?

**Comment by kkrawczynski** [comment]
@yoichitgy yeah, i put 2 ways to resolve this in my sample project (in comments)

**Comment by yoichitgy** [comment]
Thank you @kkrawczynski 🙏
