### ISSUE TITLE
ViewController Registration with Name not working?

### ISSUE THREAD

**Issue by phillippbertram** [Swinject/SwinjectStoryboard#58]
**SwinjectStoryBoard Version: 1.1.1**

Hi!

I am using Swinject for several projects and I really enjoy that project! :)
Now I just want to try out a ViewController registration with name, because I need the same ViewController type but with different dependency (view model) instances. Unfortunately this dependency is never set and the `initCompleted` closure from `storyboardInitCompleted` is never called.

Maybe I am using it in a wrong way? Here is some example code extract of my current project.

**ViewController Storyboard Ids**
2 Storyboard ViewControllers of class `MyViewController`
1. Storyboard ID: "active"
2. Storyboard ID: "inactive"

**ViewController registration**
```swift
container.storyboardInitCompleted(MyViewController.self, name: "active") { resolver, vc in
            vc.viewModel = resolver.resolve(MyViewModelType.self, name: "active")
}

container.storyboardInitCompleted(MyViewController.self, name: "inactive") { resolver, vc in
            vc.viewModel = resolver.resolve(MyViewModelType.self, name: "inactive")
}
```

**ViewModel registration**
```swift
container.register(MyViewModelType.self, name: "active") { resolver in
            return MyViewModel(filter: .active)                  
}

container.register(MyViewModelType.self, name: "inactive") { resolver in
            return MyViewModel(filter: .inactive)                  
}
```

**ViewController Instantiation**

```swift
let activeViewController = storyboard.instantiateViewController(withIdentifier: "active")
let inactiveViewController = storyboard.instantiateViewController(withIdentifier: "inactive")

activeViewController.viewModel  // <- nil
inactiveViewController.viewModel // <- nil
```

In `SinjectStoryBoard.injectDependency` there is `nil` in `registrationName` (Line 94 in File ViewController+Swinject.swift). Maybe that causes the problem?

Thank you and kind regards
Phillipp

**Comment by jakubvano** [comment]
Hi @phillippbertram ,

Indeed, SwinjectStoryboard is **not using** StoryboardID to match registration names but `registrationName` attribute instead - how you specify it via storyboard is described [here](https://github.com/Swinject/SwinjectStoryboard#registration)

**Comment by ichina** [comment]
how to pass parameters to resolver in 
`container.storyboardInitCompleted(AnimalController.self, name: "Animals") { resolver, vc in
            vc.viewModel = resolver.resolve(MyViewModelType.self, name: "inactive")
}`
`let sb = SwinjectStoryboard.create(
    name: "Animals", bundle: nil, container: container)`
`let controller = sb.instantiateViewControllerWithIdentifier("Animal")
    as! AnimalController
`
like in typical container:
`container.register(MyViewModelType.self, name: "inactive") { resolver, parameter in
            return MyViewModel(filter: parameter)                  
}`
`container.resolve(MyViewModelType.self, argument: parameter)`
?

**Comment by phillippbertram** [comment]
thanks @jakubvano
I obviously overlooked that! Maybe this important sentence should be more highlighted :D
