### ISSUE TITLE
Swinject crashes swiftc in Xcode 9

### ISSUE THREAD

**Issue by sashagood** [Swinject/SwinjectStoryboard#59]
Segmentation fault happens when using SwinjectStoryboard and Swinject (swift4 branch). Have anybody investigated that?

That happens if we pass the controller as protocol (**ProjectsListViewInputProtocol**).

```
container.storyboardInitCompleted(ProjectsListViewController.self) { (r, controller: ProjectsListViewInputProtocol) in
            let presenter = r.resolve(ProjectsListPresenterProtocol.self, argument: controller)!
            controller.presenter = presenter
}
```

**Comment by yoichitgy** [comment]
I still didn't try Swinject with Xcode 9 beta. I'll check the issue.

**Comment by sashagood** [comment]
@yoichitgy Thank you. Looking forward to hearing from you

**Comment by yoichitgy** [comment]
It looks Xcode 9 beta 6 fixed the crash issue. Please reopen this issue if you still see the carsh🙏

**Comment by sashagood** [comment]
@yoichitgy Thx!
