### ISSUE TITLE
SwinjectStoryboard setup function no longer called automatically

### ISSUE THREAD

**Issue by ThomasLeblond** [Swinject/SwinjectStoryboard#63]
Hello,

I'am starting a new project on Xcode 9 beta 5 (and tested today on beta 6) and the static function `setup()` is no longer called automatically. I need to call it manually in AppDelegate. But the issue with this workaround, the initial view controller is not injected only the next are injected.

Anybody have the same issue ?

Thank for helping.

**Comment by yoichitgy** [comment]
We are working on the issue now (PR #46).
