### ISSUE TITLE
Storyboard injection with `Assembly`

### ISSUE THREAD

**Issue by atomicbird** [Swinject/SwinjectStoryboard#65]
I'm working on an app that uses Swinject via the [`Assembly`](https://github.com/Swinject/Swinject/blob/master/Documentation/Assembler.md) approach to managing injection. I'm looking at adding support for storyboard injection.

Since we're currently instantiating the window and main view controller from the storyboard, I think I need to use `SwinjectStoryboard.setup()` to manage storyboard injection. But the `defaultContainer` used there isn't the same as the `container` argument passed to my `Assembly` subclass. Also, `setup()` is called early enough that I don't think I can create my assembly objects before `setup()` is called.

Is there some way I can use SwinjectStoryboard to manage a dependency on an object that's created in an `Assembly`? It's possible I haven't grasped Swinject well enough to see the obvious approach here.

**Comment by yoichitgy** [comment]
Thanks @mpdifran for the answer👍
