### ISSUE TITLE
Injection not working in Xcode 9 and Swift 4

### ISSUE THREAD

**Issue by charles-oder** [Swinject/SwinjectStoryboard#72]
I have recently upgraded a project to Xcode 9 and Swift 4.

The SwinjectStoryboard.setup() method is no longer firing.

also, UIViewControllers are not invoking their associated storyboardInitCompleted calls

**Comment by Sega-Zero** [comment]
@charles-oder, declare your setup method with `@objc`, it is mandatory in swift 4:
```swift
@objc class func setup() {
```

@yoichitgy, I believe, we need to update the docs mentioning that

**Comment by charles-oder** [comment]
Yep, that fixed it, thanks!

**Comment by yoichitgy** [comment]
Thanks @Sega-Zero👍 I updated README: d727183ccbb8856e4b62758140352ca6e4f927e6
