### ISSUE TITLE
No object named "swift4" exists

### ISSUE THREAD

**Issue by RustamKhisamov** [Swinject/SwinjectStoryboard#75]
When I try to update the Carthage I have this error: 
`*** Fetching SwinjectStoryboard
Failed to check out repository into /Users/user/Library/Caches/org.carthage.CarthageKit/dependencies/SwinjectStoryboard: No object named "swift4" exists (Error Domain=CarthageKit.CarthageError Code=22 "(null)")`

**Comment by RustamKhisamov** [comment]
Found an issue. Gays you forgot to create a new one release after you merge the branch "Swift4" to "master"

**Comment by yoichitgy** [comment]
I'll make a release soon. Please specify an SHA to install Swinject by Carthage👍

**Comment by jakubvano** [comment]
Should be fixed now by latest release (2.0.0-beta.1)
