### ISSUE TITLE
Controller identifier is NSStoryboard.SceneIdentifier instead of String

### ISSUE THREAD

**Issue by dfischbach** [Swinject/SwinjectStoryboard#82]
Version 1.1.2 doesn't compile for XCode 9.2 / Swift 4 as the type of the identifier of NSStoryboard changed from String to NSStoryboard.SceneIdentifier.
…
#elseif os(OSX)
    /// Instantiates the view/Window controller with the specified identifier.
    /// The view/window controller and its child controllers have their dependencies injected
    /// as specified in the `Container` passed to the initializer of the `SwinjectStoryboard`.
    ///
    /// - Parameter identifier: The identifier set in the storyboard file.
    ///
    /// - Returns: The instantiated view/window controller with its dependencies injected.
    public override func instantiateController(withIdentifier identifier: **NSStoryboard.SceneIdentifier**) -> Any {
        SwinjectStoryboard.pushInstantiatingStoryboard(self)
        let controller = super.instantiateController(withIdentifier: identifier)
        SwinjectStoryboard.popInstantiatingStoryboard()
…

**Comment by jakubvano** [comment]
Indeed, 1.1.2 version does not support swift4, and unfortunately there is no compatible version released yet.
There is a [swift 4 PR](https://github.com/Swinject/SwinjectStoryboard/pull/79), you can try using that [branch](https://github.com/jakubvano/SwinjectStoryboard/tree/swift4) as a workaround.

**Comment by jakubvano** [comment]
Resolved by #79 - Swift 4 for OSX is currently supported by version 2.0.0-beta.1
