### ISSUE TITLE
ViewController with custom initialiser

### ISSUE THREAD

**Issue by J7mbo** [Swinject/SwinjectStoryboard#83]
I have a controller with a custom initialiser:

```
class MyController: UIViewController {
    private let obj: MyObj! // This MUST exist, it cannot and should not be optional
    init(withObject obj: MyObject) {
        self.obj = obj
    }

    // Looks like I have to have this here...
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
}
```

How can I use SwinjectStoryboard to create this controller with the initialiser called? I can't find the documentation on this exact use case. The required init is the one that's called.

**Comment by jakubvano** [comment]
You cannot - SwinjectStoryboard is meant to be used in cases when you want to instantiate your view controllers from storyboard, i.e. cannot use custom initialiser.

For custom initialiser, just use pure Swinject:
```swift
container.register(MyViewController.self) {
    MyViewController(withObject: $0.resolve(MyObject.self)!) 
}
```

**Comment by J7mbo** [comment]
Okay, and if I want to use SwinjectStoryboard to instantiate the view controller (as it's from a storyboard), but I want this to be injected as a property of another view controller, is this possible? I have it working, but it gives me the same error that I provided in my other issue. I get an error in console, but it does indeed resolve.

**Comment by J7mbo** [comment]
Okay, I'll close this as a misunderstanding on initialising view controllers from storyboards with having an initialiser as I now realise you can't :) Thanks! I'll link this to the other one as I solved that too.
