### ISSUE TITLE
Embedded View Controllers

### ISSUE THREAD

**Issue by J7mbo** [Swinject/SwinjectStoryboard#85]
Hey guys, for the past week I’ve been having a real issue trying to get an embedded view controller to have a property injected into it by the container.

All the VCs exist in the storyboard. They are subclasses of UIVC.

- I have the initial VC initialised programmatically in AppDelegate. This is great as it is resolved from the container.
- The container view with an embed segue to VC2 does not automatically have its properties resolved.

Can the embedded VC2 have its properties resolved as well, even if it is also designed in the storyboard? I must be d

**Comment by J7mbo** [comment]
Sorry for cutting off - on mobile!

I must be doing something wrong. The examples provided are very simplistic - is there any chance you could provide an example bit of code for this registration working, if possible, for the embedded VC?

**Comment by jakubvano** [comment]
Correct me if I'm wrong: you have two view controllers - main and embedded one - both designed in the storyboard. Main one you registered and resolved using basic Swinject approach, and second one you expect to be injected via SwinjectStoryboard's `storyboardInitCompleted`?

If that is the case it is possible that there is some unexpected behaviour / bug, as I don't think such setup is very common. Can you provide some extract from the registration / resolution code, and maybe a storyboard screen shot?

**Comment by J7mbo** [comment]
Hey @jakubvano, this is correct, I've just create a simple project to test it and it looks like it doesn't work when the first view controller is registered by myself manually.

Here's two view controllers:

```
class VC1: UIViewController {
    public var test: Test?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        print(test?.getX())
    }
}

class VC2: UIViewController {
    public var test: Test?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        print(test?.getX())
    }
}

struct Test {
    let x = arc4random()
    
    func getX() -> Any {
        return self.x
    }
}
```

Here's the container registration and programmatic initialisation of the initial view controller in `AppDelegate`:

```
let c = Container()
        
        c.autoregister(Test.self, initializer: Test.init)
        
        c.storyboardInitCompleted(VC1.self) { r, c in c.test = r.resolve(Test.self) }
        c.storyboardInitCompleted(VC2.self) { r, c in c.test = r.resolve(Test.self) }
        
        self.window = self.window ?? UIWindow(frame: UIScreen.main.bounds)
       
        let vc1 = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "VC1") as! VC1
        
        self.window?.rootViewController = vc1
        self.window?.makeKeyAndVisible()
        
        return true
```
