### ISSUE TITLE
SwinjectStoryboard don't work with Cocoapods 1.5.0

### ISSUE THREAD

**Issue by mackoj** [Swinject/SwinjectStoryboard#86]
Next version of Cocoapods add static library support for Swift.

In `SwinjectStoryboard+SetUp.m` I have `'SwinjectStoryboard/SwinjectStoryboard-Swift.h' file not found`.

**Comment by jakubvano** [comment]
I haven't been able to reproduce the issue using
```
cocoapods 1.5.0.beta.1
Xcode 9.2
SwinjectStoryboard 1.1.2
```
Can you provide more info about the issue?

**Comment by mackoj** [comment]
I have made this empty project to show the issue.
I have the same configuration.

```
cocoapods 1.5.0.beta.1
Xcode 9.2
```

[testSwinjectStoryboard.zip](https://github.com/Swinject/SwinjectStoryboard/files/1851120/testSwinjectStoryboard.zip)

**Comment by jakubvano** [comment]
I see, it does not work properly with the new `use_frameworks!(false)` directive. 

As I mentioned in #87 we don't want to force the static framework on all the users (which was the only option until cocoapods 1.4.0), but we should make it possible to build SwinjectStoryboard as static library if user chooses to do so.

Thanks for pointing this out! 👍

**Comment by mackoj** [comment]
Thanks for your stewardship of this project.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
