### ISSUE TITLE
Cannot convert value of type 'Container.Controller' (aka 'UIViewController') to closure result type 'Any'

### ISSUE THREAD

**Issue by phatfly** [Swinject/SwinjectStoryboard#89]
Hello,
I am just starting a new project today and have been having an issue with this error:

Cannot convert value of type 'Container.Controller' (aka 'UIViewController') to closure result type 'Any'

It's at line 108 in SwinjectStoryboard.swift.

Is this a known issue?

Thanks.

Xcode 9.2
Swift 4
pod 'SwinjectStoryboard', '1.1.2'

**Comment by zarochintsev** [comment]
Hi, yes, i have the same problem when `Swinject v2.3.0` and `SwinjectStoryboard v1.1.2`, but when i use `Swinject v2.2.0`everything is fine.

**Comment by phatfly** [comment]
Golden!  That combination worked.  Thank you for the quick response!

**Comment by pastmos** [comment]
Yes, it works! The problem has just appeared after pod update, with SwinjectStoryboard 2.3.0. If you change for 2.2.0 it's all goes fine. Thanks a lot! Saved my day

**Comment by jakubvano** [comment]
Resolved by #88.

Indeed, 1.1.2 is not compatible with Swinject 2.3.0. 1.2.0 fixes the issue, and has already been released.

**Comment by ihorodnikoff** [comment]
Still not work in Swinject 2.3.0. SwinjectStoryboard 1.2.0

**Comment by zarochintsev** [comment]
@jakubvano Oops, the problem has remained.

**Comment by jakubvano** [comment]
I see, the issue remained due to the Swift3 / Swift4 differences: `1.2.x` is intended to be fully compatible with Swift3 and unfortunately build was not tested with Swift4 compilation.

Should be resolved by #91

**Comment by zarochintsev** [comment]
@jakubvano Good job! Thanks you!

**Comment by jakubvano** [comment]
1.2.1 has been released, as well as 2.0.0-beta.1 which includes Swift4 compatibility for OSX
